
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author danis
 */
public class Admin_Login extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Login
     */
    public Admin_Login() {
        initComponents();
        setSize(500, 500);
        setVisible(true);
         getContentPane().setBackground(new Color(153,255,204));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        j_username = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        j_admin_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Admin Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 240, 60);

        jLabel2.setText("Enter Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 140, 180, 50);

        jLabel3.setText("Enter Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 230, 190, 50);
        getContentPane().add(j_username);
        j_username.setBounds(190, 150, 230, 50);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(190, 230, 230, 50);

        j_admin_login.setText("Login");
        j_admin_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_admin_loginActionPerformed(evt);
            }
        });
        getContentPane().add(j_admin_login);
        j_admin_login.setBounds(140, 340, 140, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_admin_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_admin_loginActionPerformed
        // TODO add your handling code here:
        String username = j_username.getText().toString();
        String password = jPasswordField1.getText().toString();
        
        if(username.equals("") || password.equals("")){
            JOptionPane.showMessageDialog(rootPane, "All fields are required.");
        }
        else {
            try {
                // create request
                
                HttpResponse<String> httpResponse = Unirest.get(GlobalClass.ip+"admin_login")
                        .queryString("username",username)
                        .queryString("password",password)
                        .asString();
                
                if(httpResponse.getStatus() == 200){
                    
                String res = httpResponse.getBody();
                
                
                if(res.equals("success")){
                    Admin_Home obj = new Admin_Home(username);
                    dispose();
                }
                else {
                    JOptionPane.showMessageDialog(rootPane, res);
                }
                
                
            }
                
                
                
                
                
                
            } catch (Exception ex) {
                Logger.getLogger(Admin_Login.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
        }
        
    }//GEN-LAST:event_j_admin_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton j_admin_login;
    private javax.swing.JTextField j_username;
    // End of variables declaration//GEN-END:variables
}
