
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author danis
 */
public class Admin_changePassword extends javax.swing.JFrame {

    /**
     * Creates new form Admin_changePassword
     */
    String username;
    public Admin_changePassword(String username) {
        initComponents();
        this.username  = username;
        setSize(500, 600);
        setVisible(true);
        j_user.setText(username);
        j_user.setEditable(false);
         getContentPane().setBackground(new Color(153,255,204));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        j_user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        j_old_pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        j_new_pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        j_confirm_pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 60, 140, 60);
        getContentPane().add(j_user);
        j_user.setBounds(180, 70, 220, 40);

        jLabel2.setText("Old Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 160, 130, 50);
        getContentPane().add(j_old_pass);
        j_old_pass.setBounds(180, 160, 220, 50);

        jLabel3.setText("New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 260, 110, 60);
        getContentPane().add(j_new_pass);
        j_new_pass.setBounds(180, 260, 220, 40);

        jLabel4.setText("Confirm New Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 370, 130, 40);
        getContentPane().add(j_confirm_pass);
        j_confirm_pass.setBounds(180, 350, 230, 50);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 440, 150, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String oldpass = j_old_pass.getText().toString();
        String newpass = j_new_pass.getText().toString();
        String confirmpass = j_confirm_pass.getText().toString();
        
        if(oldpass.equals("") || newpass.equals("") || confirmpass.equals("")){
            JOptionPane.showMessageDialog(rootPane, " All fields are required");
        }
        else if(newpass.equals(confirmpass)){
            try {
                
                HttpResponse<String> httpResponse = Unirest.get(GlobalClass.ip+"admin_change_pass")
                        .queryString("username",username)
                        .queryString("oldpass",oldpass)
                        .queryString("newpass",newpass)
                        .asString();
                
                if(httpResponse.getStatus() == 200 ){
                    String res = httpResponse.getBody();
                    JOptionPane.showMessageDialog(rootPane, res);
                }
                
                
                
                
            } catch (UnirestException ex) {
                Logger.getLogger(Admin_changePassword.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        else {
            JOptionPane.showMessageDialog(rootPane, " New password and confirm password must match.");
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Admin_changePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField j_confirm_pass;
    private javax.swing.JPasswordField j_new_pass;
    private javax.swing.JPasswordField j_old_pass;
    private javax.swing.JTextField j_user;
    // End of variables declaration//GEN-END:variables
}
