
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author danis
 */
public class Admin_Add_Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Add_Rooms
     */
    JFileChooser jfc = new JFileChooser();
    File obj_file;
    public Admin_Add_Rooms() {
        initComponents();
        setVisible(true);
        setSize(500,500);
        cb_category.removeAllItems();
         getContentPane().setBackground(new Color(153,255,204));
        for (int i = 0; i < GlobalClass.category.length; i++) {
            cb_category.addItem(GlobalClass.category[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_category = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        j_room = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        j_photo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 62, 140, 40);

        cb_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cb_category);
        cb_category.setBounds(220, 70, 220, 40);

        jLabel2.setText("Room Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 160, 130, 40);
        getContentPane().add(j_room);
        j_room.setBounds(210, 160, 230, 40);

        jLabel3.setText("Photo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 250, 110, 40);

        j_photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(j_photo);
        j_photo.setBounds(200, 250, 150, 130);

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 290, 110, 40);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 410, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int ans = jfc.showOpenDialog(this);
        if(ans == JFileChooser.APPROVE_OPTION){
            obj_file = jfc.getSelectedFile();
            System.out.println(""+obj_file.getAbsolutePath());
            j_photo.setText(obj_file.getPath());
            
            //set image into label
            ImageIcon icon = new ImageIcon(obj_file.getPath());
            Image img = icon.getImage();
            Image newimage  = img.getScaledInstance(j_photo.getWidth(), j_photo.getHeight(),Image.SCALE_SMOOTH);
            
            j_photo.setIcon(new ImageIcon(newimage));
            
            
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String category = cb_category.getSelectedItem().toString();
        String roomname = j_room.getText().toString();
        if(roomname.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "All Fields are Required");
        }
        else {
            try {
                HttpResponse<String> httpResponse = Unirest.post(GlobalClass.ip+"add_rooms")
                        .queryString("category",category)
                        .queryString("roomname",roomname)
                        .field("photo", obj_file)
                        .asString();
                
                if(httpResponse.getStatus() == 200){
                    String res = httpResponse.getBody();
                   JOptionPane.showMessageDialog(rootPane, res);
                   dispose();
                }
                
                
                
            } catch (UnirestException ex) {
                Logger.getLogger(Admin_Add_Rooms.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Add_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Add_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Add_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Add_Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Add_Rooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_category;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel j_photo;
    private javax.swing.JTextField j_room;
    // End of variables declaration//GEN-END:variables
}
