/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author danis
 */
public class category_Pannel extends javax.swing.JPanel {

    /**
     * Creates new form category_Pannel
     */
    public category_Pannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_text = new javax.swing.JLabel();
        jScrollPanecategory = new javax.swing.JScrollPane();
        j_cat_pannel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 255, 255));
        setLayout(null);

        j_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(j_text);
        j_text.setBounds(70, 20, 260, 40);

        j_cat_pannel.setBackground(new java.awt.Color(255, 255, 153));
        j_cat_pannel.setLayout(null);
        jScrollPanecategory.setViewportView(j_cat_pannel);

        add(jScrollPanecategory);
        jScrollPanecategory.setBounds(50, 90, 480, 160);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPanecategory;
    public javax.swing.JPanel j_cat_pannel;
    public javax.swing.JLabel j_text;
    // End of variables declaration//GEN-END:variables
}
