/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author danis
 */
public class Pannel_Design extends javax.swing.JPanel {

    /**
     * Creates new form Pannel_Design
     */
    public Pannel_Design() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 255));
        setLayout(null);

        j_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(j_text);
        j_text.setBounds(50, 30, 280, 80);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel j_text;
    // End of variables declaration//GEN-END:variables
}
