/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author danis
 */
public class Rooms_Pannel extends javax.swing.JPanel {

    /**
     * Creates new form Rooms_Pannel
     */
    public Rooms_Pannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jroomimg = new javax.swing.JLabel();
        jroomtext = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(null);

        jroomimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jroomimg);
        jroomimg.setBounds(40, 20, 150, 120);

        jroomtext.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(jroomtext);
        jroomtext.setBounds(40, 150, 150, 60);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jroomimg;
    public javax.swing.JLabel jroomtext;
    // End of variables declaration//GEN-END:variables
}
