
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author danis
 */
public class User_Signup extends javax.swing.JFrame {

    /**
     * Creates new form User_Signup
     */
    JFileChooser jfc = new JFileChooser();
    File obj_file;
    public User_Signup() {
        initComponents();
        setSize(600,500);
        setVisible(true);
         getContentPane().setBackground(new Color(153,255,204));
        j_sec_ques.removeAllItems();
        for (int i = 0; i < GlobalClass.Sec_ques.length; i++) {
            j_sec_ques.addItem(GlobalClass.Sec_ques[i]);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        j_img = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        juser = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jpass1 = new javax.swing.JPasswordField();
        jconpass = new javax.swing.JPasswordField();
        jphone = new javax.swing.JTextField();
        j_sec_ques = new javax.swing.JComboBox<>();
        j_secans = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 61, 170, 30);

        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 120, 150, 40);

        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 180, 150, 50);

        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 250, 150, 50);

        jLabel5.setText("Mobile number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 320, 160, 50);

        jLabel6.setText("Security Question");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 390, 110, 40);

        jLabel7.setText("Security Ans");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 450, 120, 40);

        jLabel8.setText("Photo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 510, 110, 40);

        j_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(j_img);
        j_img.setBounds(180, 510, 160, 100);

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 540, 67, 23);

        jButton2.setText("Signup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 630, 150, 50);
        getContentPane().add(juser);
        juser.setBounds(200, 60, 230, 40);
        getContentPane().add(jemail);
        jemail.setBounds(200, 130, 230, 40);
        getContentPane().add(jpass1);
        jpass1.setBounds(200, 190, 230, 40);
        getContentPane().add(jconpass);
        jconpass.setBounds(200, 260, 230, 40);
        getContentPane().add(jphone);
        jphone.setBounds(200, 330, 230, 30);

        j_sec_ques.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(j_sec_ques);
        j_sec_ques.setBounds(200, 390, 230, 40);
        getContentPane().add(j_secans);
        j_secans.setBounds(190, 460, 240, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
          int ans = jfc.showOpenDialog(this);
        if(ans == JFileChooser.APPROVE_OPTION){
            obj_file = jfc.getSelectedFile();
            System.out.println(""+obj_file.getAbsolutePath());
            j_img.setText(obj_file.getPath());
            
            //set image into label
            ImageIcon icon = new ImageIcon(obj_file.getPath());
            Image img = icon.getImage();
            Image newimage  = img.getScaledInstance(j_img.getWidth(), j_img.getHeight(),Image.SCALE_SMOOTH);
            
            j_img.setIcon(new ImageIcon(newimage));
            
            
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String username = juser.getText().toString();
        String pass = jpass1.getText().toString();
        String confirmpass = jconpass.getText().toString();
        String email = jemail.getText().toString();
        String mobileno = jphone.getText().toString();
        String sec_ques = j_sec_ques.getSelectedItem().toString();
        String sec_ans = j_secans.getText().toString();
        if(username.isEmpty() || pass.equals("") || confirmpass.isEmpty() || email.isEmpty() || mobileno.isEmpty()
                || sec_ans.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "All Fields are required..");
        }
        else if (pass.equals(confirmpass)){
            try {
                HttpResponse<String> httpResponse = Unirest.post(GlobalClass.ip+"user_signup")
                        .queryString("username",username)
                        .queryString("password",pass)
                        .queryString("email",email)
                        .queryString("mobileno",mobileno)
                        .queryString("sec_ques",sec_ques)
                        .queryString("sec_ans",sec_ans)
                        .field("photo", obj_file)
                        .asString();
                if(httpResponse.getStatus() == 200){
                    String res  = httpResponse.getBody();
                    JOptionPane.showMessageDialog(rootPane, res);
                }
                
                
                
            } catch (UnirestException ex) {
                Logger.getLogger(User_Signup.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Password and confirm passwrod Must match");
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel j_img;
    private javax.swing.JComboBox<String> j_sec_ques;
    private javax.swing.JTextField j_secans;
    private javax.swing.JPasswordField jconpass;
    private javax.swing.JTextField jemail;
    private javax.swing.JPasswordField jpass1;
    private javax.swing.JTextField jphone;
    private javax.swing.JTextField juser;
    // End of variables declaration//GEN-END:variables
}
