
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author danis
 */
public class User_Home extends javax.swing.JFrame {

    /**
     * Creates new form User_Home
     */
    int x = 10, y = 10;
    String username;
    int width, h;

    public User_Home(String username) {
   
        initComponents();
        setVisible(true);
 getContentPane().setBackground(new Color(153,255,204));
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        width = d.width;
        h = d.height;
        setSize(width, h);
        this.username = username;

        juser.setText("Welcome :- " + username);
        jPanel1.setBounds(10, 10, width, 150);

        jScrollPane1.setBounds(10, 170, width - 50, h - 200);
        mainpannel.setPreferredSize(new Dimension(width * 2, h * 2));

        get_allcategory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainpannel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        juser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mainpannel.setBackground(new java.awt.Color(51, 255, 51));
        mainpannel.setPreferredSize(new java.awt.Dimension(10000, 10000));
        mainpannel.setLayout(null);
        jScrollPane1.setViewportView(mainpannel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 710, 310);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(null);
        jPanel1.add(juser);
        juser.setBounds(30, 20, 220, 60);

        jButton1.setText("Change Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(430, 20, 170, 50);

        jButton3.setText("MyRooms");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(970, 20, 190, 60);

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(690, 20, 190, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 1180, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        User_Change_password obj = new User_Change_password(username);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        User_Login obj = new User_Login();
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        User_Follow_Rooms obj = new User_Follow_Rooms(username);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new User_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel juser;
    private javax.swing.JPanel mainpannel;
    // End of variables declaration//GEN-END:variables

    public void get_allcategory() {
        category_Pannel cp[] = new category_Pannel[GlobalClass.category.length];

        for (int i = 0; i < GlobalClass.category.length; i++) {

            cp[i] = new category_Pannel();

            cp[i].setBounds(x, y, width, 330);
            y = y + 340;

            cp[i].j_text.setText(GlobalClass.category[i]);

            cp[i].j_cat_pannel.setPreferredSize(new Dimension(width * 2, 300));
            cp[i].jScrollPanecategory.setBounds(50, 80, width, 250);

            try {
                // UNirest Req
                HttpResponse<String> httpResponse = Unirest.get(GlobalClass.ip + "fetch_rooms_cat")
                        .queryString("category", GlobalClass.category[i])
                        .asString();
                if (httpResponse.getStatus() == 200) {
                    String res = httpResponse.getBody();
                    StringTokenizer st = new StringTokenizer(res, "~~");
                    int j = 0, m = 10, n = 10;
                    Rooms_Pannel rp[] = new Rooms_Pannel[st.countTokens()];

                    while (st.hasMoreTokens()) {
                        String res2 = st.nextToken();
                        StringTokenizer st2 = new StringTokenizer(res2, "$$");
//                         while(st2.hasMoreTokens()){
rp[j] = new Rooms_Pannel();
                        int rid = Integer.parseInt(st2.nextToken());
                        String roomname = st2.nextToken();
                        String photo = st2.nextToken();
                        String cat = st2.nextToken();
                        ImageIcon icon = new ImageIcon("");
                        BufferedImage bufferedImage = null, newimage;

                        try {
                            URL url = new URL(GlobalClass.ip + "GetResource/" + photo);
                            System.out.println("url : " + url);
                            bufferedImage = ImageIO.read(url);
                        } catch (Exception ex) {
                            Logger.getLogger(User_Home.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        newimage = resizephoto(bufferedImage, rp[j].jroomimg.getWidth(), rp[j].jroomimg.getHeight());
                        icon = new ImageIcon(newimage);
                        
                       System.out.println("" + roomname);
                        
                        rp[j].setBounds(m, n, 250, 230);
//                        rp[j].jroomimg.setText(photo);
                        rp[j].jroomtext.setText(roomname);
                        rp[j].jroomimg.setIcon(icon);

                        m = m + 260;

                        rp[j].addMouseListener(new MouseAdapter() {
                            @Override
                            public void mouseClicked(MouseEvent e) {
//                                super.mouseClicked(e); //To change body of generated methods, choose Tools | Templates.
                                if (e.getClickCount() == 1) {
                                   Group_chat obj = new Group_chat(rid,username);
                                }

                            }

                        });
                        cp[i].j_cat_pannel.add(rp[j]);
                        repaint();

//                         }
                        j++;
                    }
                }

            } catch (UnirestException ex) {
                Logger.getLogger(User_Home.class.getName()).log(Level.SEVERE, null, ex);
            }

            mainpannel.add(cp[i]);
            repaint();
            mainpannel.repaint();
        }
    }

    BufferedImage resizephoto(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

}
