
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author danis
 */
public class User_Change_password extends javax.swing.JFrame {

    /**
     * Creates new form User_Change_password
     */
    String username;
    public User_Change_password(String username) {
        initComponents();
        setSize(500,500);
        setVisible(true);
        this.username = username;
        juser.setText(username);
        juser.setEditable(false);
         getContentPane().setBackground(new Color(153,255,204));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        juser = new javax.swing.JTextField();
        jpass = new javax.swing.JPasswordField();
        jnewpass = new javax.swing.JPasswordField();
        jconfirmpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(18, 11, 190, 51);

        jLabel2.setText("Old password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 160, 60);

        jLabel3.setText("New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 160, 60);

        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 270, 140, 50);
        getContentPane().add(juser);
        juser.setBounds(200, 20, 210, 50);
        getContentPane().add(jpass);
        jpass.setBounds(200, 100, 210, 50);
        getContentPane().add(jnewpass);
        jnewpass.setBounds(200, 190, 210, 50);
        getContentPane().add(jconfirmpass);
        jconfirmpass.setBounds(200, 270, 210, 60);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 400, 140, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String oldpass = jpass.getText();
        String newpass = jnewpass.getText();
        String confirmpass = jconfirmpass.getText();
        
        if(oldpass.isEmpty() || newpass.isEmpty() || confirmpass.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "All fileds are required");
            
        }
        else if (newpass.equals(confirmpass)){
             try {
                HttpResponse<String> httpResponse = Unirest.get(GlobalClass.ip+"user_change_pass")
                        .queryString("username",username)
                        .queryString("oldpass",oldpass)
                        .queryString("newpass",newpass)
                        .asString();
                
                if(httpResponse.getStatus() == 200){
                    String res = httpResponse.getBody();
                    JOptionPane.showMessageDialog(rootPane, res);
                }
                
            } catch (UnirestException ex) {
                Logger.getLogger(User_Change_password.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        else {
          JOptionPane.showMessageDialog(rootPane, "New Password and confirm password must match"); 
            
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new User_Change_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jconfirmpass;
    private javax.swing.JPasswordField jnewpass;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JTextField juser;
    // End of variables declaration//GEN-END:variables
}
